name: build-windows
run-name: Compilando para Windows

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: aleph.exe
        key: aleph-${{ hashFiles('src/**/*.[chyl]', 'Makefile') }}

    - name: Setup MSYS2
      if: steps.cache.outputs.cache-hit != 'true' 
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        install: "mingw-w64-ucrt-x86_64-gcc make bison flex"

    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: make

    - name: Cache binary
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: aleph.exe
        key: aleph-${{ hashFiles('src/**/*.[chyl]', 'Makefile') }}
