name: delete-runs
run-name: Eliminando ejecuciones de workflows

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Días que se conservan las ejecuciones'
        required: true
        type: number
        default: 30
      minimum_runs:
        description: 'Cantidad mínima de ejecuciones a conservar'
        required: true
        type: number
        default: 6
      delete_workflow_pattern:
        description: 'Nombre o archivo del workflow a eliminar'
        required: false
      delete_workflow_by_state_pattern:
        description: 'Eliminar por estado'
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Eliminar por conclusión'
        required: true
        default: "All"
        type: choice
        options:
          - "All"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: 'Ejecutar sin eliminar'
        required: false

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: ${{ github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ github.event.inputs.delete_run_by_conclusion_pattern }}
          dry_run: ${{ github.event.inputs.dry_run }}
