name: test-windows
run-name: Testeando en Windows

on:
  workflow_run:
    workflows: [build-windows]
    types: [completed]

jobs:
  test:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Set pending status
      uses: myrotvorets/set-commit-status-action@v2.0.1
      with:
        status: pending
        sha: ${{ github.event.workflow_run.head_sha }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore binary
      uses: actions/cache/restore@v4
      with:
        path: aleph.exe
        key: aleph-${{ hashFiles('src/**/*.[chyl]', 'Makefile') }}
        fail-on-cache-miss: true
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '>=3.10'

    - name: Run tests
      run: python test/test.py >> $env:GITHUB_STEP_SUMMARY
      env:
        PYTHONUTF8: 1

    - name: Set result status
      uses: myrotvorets/set-commit-status-action@v2.0.1
      if: always()
      with:
        status: ${{ job.status }}
        sha: ${{ github.event.workflow_run.head_sha }}
